### ISSUE TITLE
Erro de Acesso ao Diretório

### ISSUE THREAD

**Issue by rodriguesraphael** [danimaribeiro/PyTrustNFe#124]
Alguém com este mesmo erro? Segue abaixo:

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/raphael/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/raphael/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/raphael/odoo11/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/raphael/odoo11/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/raphael/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/raphael/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/raphael/odoo11/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 781, in action_send_eletronic_invoice
    retorno = resposta['object'].Body.nfeAutorizacaoLoteResult
  File "src/lxml/objectify.pyx", line 230, in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/objectify.c:4457)
  File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise (src/lxml/objectify.c:7242)
AttributeError: no such child: {http://www.w3.org/1999/xhtml}Body
```

**Comment by rodriguesraphael** [comment]
O erro era certificado cancelado.
