### ISSUE TITLE
Consulta Cadastro PR - 405 Client Error: Method Not Allowed

### ISSUE THREAD

**Issue by aledr** [danimaribeiro/PyTrustNFe#159]
Olá!

Segue erro ao consultar cadastro PR:

```
2018-08-05 16:42:43,351 12565 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-287>", line 2, in action_check_sefaz
  File "/home/odoo/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-brasil/br_base/models/res_partner.py", line 201, in action_check_sefaz
    estado=self.state_id.ibge_code)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/pytrustnfe/nfe/__init__.py", line 241, in consulta_cadastro
    return _send(certificado, 'NfeConsultaCadastro', **kwargs)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/pytrustnfe/nfe/__init__.py", line 158, in _send
    client = Client(base_url, transport=transport)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/client.py", line 62, in __init__
    wsdl, self.transport, settings=self.settings)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
    document = self._get_xml_document(location)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/wsdl/wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/loader.py", line 74, in load_external
    content = transport.load(url)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/zeep/transports.py", line 127, in _load_remote_data
    response.raise_for_status()
  File "/home/odoo/odoo_11_env/lib/python3.4/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2
```

Segue saída do ```pip list```:

```
Package             Version  
------------------- ---------
appdirs             1.4.3    
asn1crypto          0.23.0   
attrs               18.1.0   
Babel               2.3.4    
beautifulsoup4      4.6.0    
cached-property     1.4.3    
certifi             2017.11.5
cffi                1.11.2   
chardet             3.0.4    
cryptography        2.3      
decorator           4.0.10   
defusedxml          0.5.0    
docutils            0.12     
ebaysdk             2.1.5    
eight               0.4.2    
feedparser          5.2.1    
future              0.16.0   
gevent              1.1.2    
greenlet            0.4.10   
html2text           2016.9.19
idna                2.6      
isodate             0.6.0    
Jinja2              2.8      
lxml                4.2.4    
Mako                1.0.4    
MarkupSafe          0.23     
mock                2.0.0    
num2words           0.5.4    
ofxparse            0.16     
passlib             1.6.5    
pbr                 3.1.1    
phonenumbers        8.8.10   
Pillow              3.4.2    
pip                 18.0     
pkgconfig           1.2.2    
psutil              4.3.1    
psycopg2            2.7.3    
pycparser           2.18     
pydot               1.2.3    
pyldap              2.4.28   
pyOpenSSL           17.5.0   
pyparsing           2.1.10   
PyPDF2              1.26.0   
pyserial            3.1.1    
python-dateutil     2.5.3    
python-stdnum       1.7      
python3-boleto      1.0.1    
python3-cnab        0.9.0    
PyTrustNFe3         0.10.3   
pytz                2016.7   
pyusb               1.0.0    
PyYAML              3.12     
qrcode              5.3      
reportlab           3.3.0    
requests            2.11.1   
requests-toolbelt   0.8.0    
setuptools          40.0.0   
setuptools-git      1.1      
signxml             2.5.2    
six                 1.10.0   
suds-jurko          0.6      
suds-jurko-requests 1.2      
urllib3             1.23     
vatnumber           1.2      
vobject             0.9.3    
Werkzeug            0.11.11  
wheel               0.24.0   
xlrd                1.0.0    
XlsxWriter          0.9.3    
xlwt                1.3.0    
xmlsec              1.3.3    
yolk                0.4.3    
zeep                3.1.0    
```

Obrigado.

**Comment by danimaribeiro** [comment]
Corrigido provavelmente na última versão.

**Comment by aledr** [comment]
Boa tarde!

Obrigado pela correção.
Percebi que ao consultar os dados eles estão inconsistentes com a Receita e o Sintegra.
O resultado parece ser de um cadastro muito antigo das empresas (normalmente o endereço vem divergente do atual).

Obrigado.
