### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by ImplantiSolucoes** [danimaribeiro/PyTrustNFe#210]
D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\urllib3-1.24.1-py3.7.egg\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "D:/desenvolvimentos/Modulos-do-odoo/manifestacao/index.py", line 7, in <module>
    resposta = consulta_cadastro(certificado, obj=obj, ambiente=1, estado='28')
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\pytrustnfe3-1.0.30-py3.7.egg\pytrustnfe\nfe\__init__.py", line 189, in consulta_cadastro
    return _send(certificado, 'NfeConsultaCadastro', **kwargs)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\pytrustnfe3-1.0.30-py3.7.egg\pytrustnfe\nfe\__init__.py", line 97, in _send
    first_op, client = _get_client(base_url, transport)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\pytrustnfe3-1.0.30-py3.7.egg\pytrustnfe\nfe\__init__.py", line 81, in _get_client
    client = Client(base_url, transport=transport)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\client.py", line 62, in __init__
    wsdl, self.transport, settings=self.settings)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\wsdl\wsdl.py", line 82, in __init__
    document = self._get_xml_document(location)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\wsdl\wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\loader.py", line 74, in load_external
    content = transport.load(url)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\zeep-3.2.0-py3.7.egg\zeep\transports.py", line 127, in _load_remote_data
    response.raise_for_status()
  File "D:\desenvolvimentos\Modulos-do-odoo\venv\lib\site-packages\requests-2.21.0-py3.7.egg\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nfe.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx?wsdl

**Comment by ImplantiSolucoes** [comment]
(venv) D:\desenvolvimentos\Modulos-do-odoo>pip list
Package             Version
------------------- ----------
appdirs             1.4.3
asn1crypto          0.24.0
attrs               18.2.0
cached-property     1.5.1
certifi             2018.11.29
cffi                1.11.5
chardet             3.0.4
cryptography        2.4.2
defusedxml          0.5.0
eight               0.4.2
future              0.16.0
idna                2.8
isodate             0.6.0
jinja2              2.10
lxml                4.3.0
markupsafe          1.1.0
pillow              5.4.0
pip                 10.0.1
pycparser           2.19
pyopenssl           17.5.0
pytrustnfe3         1.0.30
pytz                2018.7
reportlab           3.5.12
requests            2.21.0
requests-toolbelt   0.8.0
setuptools          39.1.0
signxml             2.5.2
six                 1.12.0
suds-jurko          0.6
suds-jurko-requests 1.2
urllib3             1.24.1
zeep                3.2.0

**Comment by GustavoGSA** [comment]
Mesmo problema aqui!

**Comment by ImplantiSolucoes** [comment]
Foi corrigido
