### ISSUE TITLE
Emissão NF-e Produção Sefaz RS

### ISSUE THREAD

**Issue by paulafernanda** [danimaribeiro/PyTrustNFe#42]
Ao emitir uma nota de entrada na Produção aparece essa mensagem:

HTTPSConnectionPool(host='nfe.sefaz.rs.gov.br', port=443): Max retries exceeded with url: /ws/NfeAutorizacao/NFeAutorizacao.asmx (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f42b6bba150>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Os serviços da Sefaz estão normais no estado.

**Comment by danimaribeiro** [comment]
Acessando a URL via browser conecta normalmente?

**Comment by paulafernanda** [comment]
Pelo browser dá acesso negado, por linha de comando aparece: certificate verify failed, mas realmente não passamos nenhum certificado

**Comment by paulafernanda** [comment]
Estou utilizando o Odoo 10 para emissão da nota. Como homologação valida e retorna a autorização. Como produção, aparece time out.

**Comment by paulafernanda** [comment]
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 647, in action_send_eletronic_invoice
    resposta = autorizar_nfe(certificado, **lote)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 188, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 178, in _send
    response, obj = executar_consulta(certificado, url, cabecalho, xml_send)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/comunicacao.py", line 30, in executar_consulta
    xml_retorno = client.post_soap(xml_enviar, cabecalho)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/client.py", line 53, in post_soap
    verify=False, headers=header)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='nfe.sefaz.rs.gov.br', port=443): Max retries exceeded with url: /ws/NfeAutorizacao/NFeAutorizacao.asmx (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f254bc25990>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by danimaribeiro** [comment]
Lancei uma atualização corrigindo o problema.

**Comment by paulafernanda** [comment]
Testei ontem mesmo. Já está enviando normalmente!
Agradeço o pronto atendimento!
